stages:
  - build-image-ready
  - test
  - build-image-service
  - upload-dev
  - upload-qa
  - upload-staging-china

variables:
    APP_NAME: "apk-manager"

build_docker_service:
    stage: build-image-ready
    image: nexus.aldebaran.com:5000/sbr-ci-docker:latest
    services:
      - docker:dind
    before_script:
      # Retrieve scripts and install env
      - cp /root/scripts/*.sh .
      - ./installEnvAlpine.sh
    script:
      - ./buildImageReady.sh
    tags:
      - privileged
    only:
      changes:
        - Pipfile.lock

run_interface_tests:
    stage: test
    image: nexus.aldebaran.com:5000/sbr-python37-alpine-build-${APP_NAME}:latest
    artifacts:
      paths:
        - htmlcov
    script:
        ####  start AIOHTTP service tests ####
      - pytest --cov=service tests/
      - coverage html
    tags:
      - privileged

build_docker_image:
    stage: build-image-service
    image: nexus.aldebaran.com:5000/sbr-ci-docker:latest
    services:
      - docker:dind
    artifacts:
      paths:
        - htmlcov
    before_script:
      # Retrieve scripts and install env
      - cp /root/scripts/*.sh .
      - ./installEnvAlpine.sh
    script:
      - ./buildImageBase.sh
    tags:
      - privileged

upload-image-to-dev-global:
    stage: upload-dev
    when: manual
    services:
      - docker:dind
    image: registry-gitlab.aldebaran.com/cloud-tools/ecr_docker_image_uploader:latest
    script:
        - VERSION=${CI_COMMIT_TAG:-latest}
        - push_image_ecr.sh dev-global "$CI_REGISTRY_IMAGE:$VERSION" $APP_NAME $CI_JOB_TOKEN
    tags:
        - s3upload-websites
        - privileged

upload-image-to-qa-china:
    stage: upload-qa
    when: manual
    services:
      - docker:dind
    image: registry-gitlab.aldebaran.com/cloud-tools/ecr_docker_image_uploader:latest
    script:
        - VERSION=${CI_COMMIT_TAG:-latest}
        - push_image_ecr.sh qa-china "$CI_REGISTRY_IMAGE:$VERSION" $APP_NAME $CI_JOB_TOKEN
    tags:
        - s3upload-websites

upload-image-to-staging-china:
    stage: upload-staging-china
    when: manual
    services:
      - docker:dind
    image: registry-gitlab.aldebaran.com/cloud-tools/ecr_docker_image_uploader:latest
    script:
        - VERSION=${CI_COMMIT_TAG:-latest}
        - push_image_ecr_china.sh staging-china "$CI_REGISTRY_IMAGE:$VERSION" $APP_NAME $CI_JOB_TOKEN
    tags:
        - privileged
        - ecr_china



upload_doc_to_qa:
    image: registry-gitlab.aldebaran.com/cloud-tools/s3-static-website-uploader
    script: upload_doc_to_s3.sh qa
    tags:
        - s3upload-websites
    only:
        - tags
